### ISSUE TITLE
Proposal: Scroll to top of screen by tapping on the 'Stream' tab again

### ISSUE THREAD

**Issue by tclaus** [jhass/insporation#12]
When scrolling down a bit, an arrow up becomes visible. Nice - but not easy to reach with the thumb. 

Would be nice to scroll to the top most post, by tapping the Stream-Tab again on the lower side of the app. 'Thumb-Friendly'

**Comment by jhass** [comment]
I'm not sure, I never experienced an app doing that, so I'm not sure if it would be intuitive. We could maybe consider moving the up arrow to the bottom?

**Comment by tclaus** [comment]
The Facebook App has this behavior, 'Ebay-Kleinanzeigen'-Home,  the 'chats'-tab in Whatsapp. (The list of chats jumps to the top on seconds tap on chat-icon. At least on iOS I have seen this many times. 
The arrow in the top right corner is OK for me.

**Comment by jhass** [comment]
Mmh, turns out I'm not actually using many tabbed apps :D The Android version of Ebay Kleinanzeigen still has a navigation drawer instead of bottom navigation. So the one tabbed app I use is the Github app and it indeed shows this behavior, I just never noticed :D 

Well I guess we can just try it for a bit and still always restore it again to current behavior if it trips people up for some reason.

**Comment by jhass** [comment]
Okay, dug a bit more through what I have installed:
* Github: does it
* Reddit: does it
* DHL: does it
* Gmail: does it
* Google home: does it
* Slack: does it
* Netflix: does it
* ZDF mediathek: does it
* Arte mediathek: dos it
* Prime video: does it
* Huawei's contacts app: does it
* Huawei's gallery app: does it
* Komoot: does it

--


* Google Play Store: doesn't do it
* F-Droid: doesn't do it
* Bandsintown: doesn't do it
* BVG ticket app: doesn't do it
* Jelbi: doesn't do it
* Keybase: doesn't do it
* Airbnb: doesn't do it
* Flixbus: doesn't do it

Quite the mixed bag, but I guess there's a trend towards doing it, maybe a pattern carrying over from iOS to Android due to cross platform apps
