### ISSUE TITLE
Testflight (IOS) expired

### ISSUE THREAD

**Issue by Masek0815** [jhass/insporation#64]
The referenced Testflight version (for IOS) is expired

**Comment by jhass** [comment]
@tclaus I can't log into the appstore connect thingy due to second factor going to your phone. It fails to upload because of pending legal blabla: https://github.com/jhass/insporation/actions/runs/3296886225/jobs/5437062107#step:4:1121

Can you check?

**Comment by tclaus** [comment]
I will check. Can you also check the mail I privately sent to your account?Am 21.10.2022 um 13:50 schrieb Jonne Haß ***@***.***>:﻿
@tclaus I can't log into the appstore connect thingy due to second factor going to your phone. It fails to upload because of pending legal blabla: https://github.com/jhass/insporation/actions/runs/3296886225/jobs/5437062107#step:4:1121
Can you check?

**Comment by tclaus** [comment]
I have updated the contracts and restarted a build. 
But this will not automagically enable TestFlight (immediately)

**Comment by tclaus** [comment]
Technical issue should be fixed with #65

**Comment by tclaus** [comment]
@Masek0815 
iOS upload works again, beta app is available in TestFlight again and even available in AppStore :-)

**Comment by Masek0815** [comment]
Thankl you!
